//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeAvaliacao.Application.SVCRecuperaDados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma> turmasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idCurso {
            get {
                return this.idCursoField;
            }
            set {
                if ((this.idCursoField.Equals(value) != true)) {
                    this.idCursoField = value;
                    this.RaisePropertyChanged("idCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeCurso {
            get {
                return this.nomeCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeCursoField, value) != true)) {
                    this.nomeCursoField = value;
                    this.RaisePropertyChanged("nomeCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma> turmas {
            get {
                return this.turmasField;
            }
            set {
                if ((object.ReferenceEquals(this.turmasField, value) != true)) {
                    this.turmasField = value;
                    this.RaisePropertyChanged("turmas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turma", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Turma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno> alunosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProfessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idTurmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeTurmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor professorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno> alunos {
            get {
                return this.alunosField;
            }
            set {
                if ((object.ReferenceEquals(this.alunosField, value) != true)) {
                    this.alunosField = value;
                    this.RaisePropertyChanged("alunos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso {
            get {
                return this.cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.cursoField, value) != true)) {
                    this.cursoField = value;
                    this.RaisePropertyChanged("curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                if ((this.idCursoField.Equals(value) != true)) {
                    this.idCursoField = value;
                    this.RaisePropertyChanged("idCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProfessor {
            get {
                return this.idProfessorField;
            }
            set {
                if ((this.idProfessorField.Equals(value) != true)) {
                    this.idProfessorField = value;
                    this.RaisePropertyChanged("idProfessor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idTurma {
            get {
                return this.idTurmaField;
            }
            set {
                if ((this.idTurmaField.Equals(value) != true)) {
                    this.idTurmaField = value;
                    this.RaisePropertyChanged("idTurma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeTurma {
            get {
                return this.nomeTurmaField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeTurmaField, value) != true)) {
                    this.nomeTurmaField = value;
                    this.RaisePropertyChanged("nomeTurma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor professor {
            get {
                return this.professorField;
            }
            set {
                if ((object.ReferenceEquals(this.professorField, value) != true)) {
                    this.professorField = value;
                    this.RaisePropertyChanged("professor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Professor", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Professor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idProfessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeProfessorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idProfessor {
            get {
                return this.idProfessorField;
            }
            set {
                if ((this.idProfessorField.Equals(value) != true)) {
                    this.idProfessorField = value;
                    this.RaisePropertyChanged("idProfessor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeProfessor {
            get {
                return this.nomeProfessorField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeProfessorField, value) != true)) {
                    this.nomeProfessorField = value;
                    this.RaisePropertyChanged("nomeProfessor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTurmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turmaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAluno {
            get {
                return this.emailAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAlunoField, value) != true)) {
                    this.emailAlunoField = value;
                    this.RaisePropertyChanged("emailAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idAluno {
            get {
                return this.idAlunoField;
            }
            set {
                if ((this.idAlunoField.Equals(value) != true)) {
                    this.idAlunoField = value;
                    this.RaisePropertyChanged("idAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTurma {
            get {
                return this.idTurmaField;
            }
            set {
                if ((this.idTurmaField.Equals(value) != true)) {
                    this.idTurmaField = value;
                    this.RaisePropertyChanged("idTurma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeAluno {
            get {
                return this.nomeAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeAlunoField, value) != true)) {
                    this.nomeAlunoField = value;
                    this.RaisePropertyChanged("nomeAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma {
            get {
                return this.turmaField;
            }
            set {
                if ((object.ReferenceEquals(this.turmaField, value) != true)) {
                    this.turmaField = value;
                    this.RaisePropertyChanged("turma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVCRecuperaDados.IRecuperaDados")]
    public interface IRecuperaDados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaCurso", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaCursoResponse")]
        void adicionaCurso(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaCurso", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaCursoResponse")]
        System.Threading.Tasks.Task adicionaCursoAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaTurmaResponse")]
        void adicionaTurma(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaTurmaResponse")]
        System.Threading.Tasks.Task adicionaTurmaAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaAluno", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaAlunoResponse")]
        void adicionaAluno(SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno aluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaAluno", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaAlunoResponse")]
        System.Threading.Tasks.Task adicionaAlunoAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno aluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaProfessor", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaProfessorResponse")]
        void adicionaProfessor(SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor professor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaProfessor", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaProfessorResponse")]
        System.Threading.Tasks.Task adicionaProfessorAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor professor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarAlunosResponse")]
        void apagarAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarAlunosResponse")]
        System.Threading.Tasks.Task apagarAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/apagarProfessoresResponse")]
        void apagarProfessores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/apagarProfessoresResponse")]
        System.Threading.Tasks.Task apagarProfessoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/apagarTurmasResponse")]
        void apagarTurmas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/apagarTurmasResponse")]
        System.Threading.Tasks.Task apagarTurmasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarCursos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarCursosResponse")]
        void apagarCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarCursos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarCursosResponse")]
        System.Threading.Tasks.Task apagarCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaAlunosResponse")]
        System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno> RecuperaAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaAlunosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno>> RecuperaAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaProfessoresResponse")]
        System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor> RecuperaProfessores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaProfessoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor>> RecuperaProfessoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaCursos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaCursosResponse")]
        System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso> RecuperaCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaCursos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaCursosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso>> RecuperaCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaTurmasResponse")]
        System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma> RecuperaTurmas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaTurmasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma>> RecuperaTurmasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaResponse")]
        System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno> ListaDeAlunosDaTurma(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno>> ListaDeAlunosDaTurmaAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCurso", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCursoResponse")]
        System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma> ListaDeTurmasDoCurso(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCurso", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCursoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma>> ListaDeTurmasDoCursoAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecuperaDadosChannel : SistemaDeAvaliacao.Application.SVCRecuperaDados.IRecuperaDados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecuperaDadosClient : System.ServiceModel.ClientBase<SistemaDeAvaliacao.Application.SVCRecuperaDados.IRecuperaDados>, SistemaDeAvaliacao.Application.SVCRecuperaDados.IRecuperaDados {
        
        public RecuperaDadosClient() {
        }
        
        public RecuperaDadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecuperaDadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperaDadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperaDadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void adicionaCurso(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso) {
            base.Channel.adicionaCurso(curso);
        }
        
        public System.Threading.Tasks.Task adicionaCursoAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso) {
            return base.Channel.adicionaCursoAsync(curso);
        }
        
        public void adicionaTurma(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma) {
            base.Channel.adicionaTurma(turma);
        }
        
        public System.Threading.Tasks.Task adicionaTurmaAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma) {
            return base.Channel.adicionaTurmaAsync(turma);
        }
        
        public void adicionaAluno(SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno aluno) {
            base.Channel.adicionaAluno(aluno);
        }
        
        public System.Threading.Tasks.Task adicionaAlunoAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno aluno) {
            return base.Channel.adicionaAlunoAsync(aluno);
        }
        
        public void adicionaProfessor(SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor professor) {
            base.Channel.adicionaProfessor(professor);
        }
        
        public System.Threading.Tasks.Task adicionaProfessorAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor professor) {
            return base.Channel.adicionaProfessorAsync(professor);
        }
        
        public void apagarAlunos() {
            base.Channel.apagarAlunos();
        }
        
        public System.Threading.Tasks.Task apagarAlunosAsync() {
            return base.Channel.apagarAlunosAsync();
        }
        
        public void apagarProfessores() {
            base.Channel.apagarProfessores();
        }
        
        public System.Threading.Tasks.Task apagarProfessoresAsync() {
            return base.Channel.apagarProfessoresAsync();
        }
        
        public void apagarTurmas() {
            base.Channel.apagarTurmas();
        }
        
        public System.Threading.Tasks.Task apagarTurmasAsync() {
            return base.Channel.apagarTurmasAsync();
        }
        
        public void apagarCursos() {
            base.Channel.apagarCursos();
        }
        
        public System.Threading.Tasks.Task apagarCursosAsync() {
            return base.Channel.apagarCursosAsync();
        }
        
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno> RecuperaAlunos() {
            return base.Channel.RecuperaAlunos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno>> RecuperaAlunosAsync() {
            return base.Channel.RecuperaAlunosAsync();
        }
        
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor> RecuperaProfessores() {
            return base.Channel.RecuperaProfessores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Professor>> RecuperaProfessoresAsync() {
            return base.Channel.RecuperaProfessoresAsync();
        }
        
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso> RecuperaCursos() {
            return base.Channel.RecuperaCursos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso>> RecuperaCursosAsync() {
            return base.Channel.RecuperaCursosAsync();
        }
        
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma> RecuperaTurmas() {
            return base.Channel.RecuperaTurmas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma>> RecuperaTurmasAsync() {
            return base.Channel.RecuperaTurmasAsync();
        }
        
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno> ListaDeAlunosDaTurma(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma) {
            return base.Channel.ListaDeAlunosDaTurma(turma);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Aluno>> ListaDeAlunosDaTurmaAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma turma) {
            return base.Channel.ListaDeAlunosDaTurmaAsync(turma);
        }
        
        public System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma> ListaDeTurmasDoCurso(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso) {
            return base.Channel.ListaDeTurmasDoCurso(curso);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SistemaDeAvaliacao.Application.SVCRecuperaDados.Turma>> ListaDeTurmasDoCursoAsync(SistemaDeAvaliacao.Application.SVCRecuperaDados.Curso curso) {
            return base.Channel.ListaDeTurmasDoCursoAsync(curso);
        }
    }
}
