//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.RecuperaDados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestApp.RecuperaDados.Turma> turmasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idCurso {
            get {
                return this.idCursoField;
            }
            set {
                if ((this.idCursoField.Equals(value) != true)) {
                    this.idCursoField = value;
                    this.RaisePropertyChanged("idCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeCurso {
            get {
                return this.nomeCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeCursoField, value) != true)) {
                    this.nomeCursoField = value;
                    this.RaisePropertyChanged("nomeCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TestApp.RecuperaDados.Turma> turmas {
            get {
                return this.turmasField;
            }
            set {
                if ((object.ReferenceEquals(this.turmasField, value) != true)) {
                    this.turmasField = value;
                    this.RaisePropertyChanged("turmas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turma", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Turma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> alunosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProfessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idTurmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.RecuperaDados.Modulo moduloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeTurmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.RecuperaDados.Professor professorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> alunos {
            get {
                return this.alunosField;
            }
            set {
                if ((object.ReferenceEquals(this.alunosField, value) != true)) {
                    this.alunosField = value;
                    this.RaisePropertyChanged("alunos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                if ((this.idModuloField.Equals(value) != true)) {
                    this.idModuloField = value;
                    this.RaisePropertyChanged("idModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProfessor {
            get {
                return this.idProfessorField;
            }
            set {
                if ((this.idProfessorField.Equals(value) != true)) {
                    this.idProfessorField = value;
                    this.RaisePropertyChanged("idProfessor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idTurma {
            get {
                return this.idTurmaField;
            }
            set {
                if ((this.idTurmaField.Equals(value) != true)) {
                    this.idTurmaField = value;
                    this.RaisePropertyChanged("idTurma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.RecuperaDados.Modulo modulo {
            get {
                return this.moduloField;
            }
            set {
                if ((object.ReferenceEquals(this.moduloField, value) != true)) {
                    this.moduloField = value;
                    this.RaisePropertyChanged("modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeTurma {
            get {
                return this.nomeTurmaField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeTurmaField, value) != true)) {
                    this.nomeTurmaField = value;
                    this.RaisePropertyChanged("nomeTurma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.RecuperaDados.Professor professor {
            get {
                return this.professorField;
            }
            set {
                if ((object.ReferenceEquals(this.professorField, value) != true)) {
                    this.professorField = value;
                    this.RaisePropertyChanged("professor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modulo", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Modulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.RecuperaDados.Bloco blocoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestApp.RecuperaDados.Turma> turmasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.RecuperaDados.Bloco bloco {
            get {
                return this.blocoField;
            }
            set {
                if ((object.ReferenceEquals(this.blocoField, value) != true)) {
                    this.blocoField = value;
                    this.RaisePropertyChanged("bloco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idModulo {
            get {
                return this.idModuloField;
            }
            set {
                if ((this.idModuloField.Equals(value) != true)) {
                    this.idModuloField = value;
                    this.RaisePropertyChanged("idModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeModulo {
            get {
                return this.nomeModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeModuloField, value) != true)) {
                    this.nomeModuloField = value;
                    this.RaisePropertyChanged("nomeModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TestApp.RecuperaDados.Turma> turmas {
            get {
                return this.turmasField;
            }
            set {
                if ((object.ReferenceEquals(this.turmasField, value) != true)) {
                    this.turmasField = value;
                    this.RaisePropertyChanged("turmas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Professor", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Professor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataAdmissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idProfessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeProfessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataAdmissao {
            get {
                return this.dataAdmissaoField;
            }
            set {
                if ((this.dataAdmissaoField.Equals(value) != true)) {
                    this.dataAdmissaoField = value;
                    this.RaisePropertyChanged("dataAdmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idProfessor {
            get {
                return this.idProfessorField;
            }
            set {
                if ((this.idProfessorField.Equals(value) != true)) {
                    this.idProfessorField = value;
                    this.RaisePropertyChanged("idProfessor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeProfessor {
            get {
                return this.nomeProfessorField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeProfessorField, value) != true)) {
                    this.nomeProfessorField = value;
                    this.RaisePropertyChanged("nomeProfessor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((this.tituloField.Equals(value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTurmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeAlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.RecuperaDados.Turma turmaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAluno {
            get {
                return this.emailAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAlunoField, value) != true)) {
                    this.emailAlunoField = value;
                    this.RaisePropertyChanged("emailAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idAluno {
            get {
                return this.idAlunoField;
            }
            set {
                if ((this.idAlunoField.Equals(value) != true)) {
                    this.idAlunoField = value;
                    this.RaisePropertyChanged("idAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTurma {
            get {
                return this.idTurmaField;
            }
            set {
                if ((this.idTurmaField.Equals(value) != true)) {
                    this.idTurmaField = value;
                    this.RaisePropertyChanged("idTurma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeAluno {
            get {
                return this.nomeAlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeAlunoField, value) != true)) {
                    this.nomeAlunoField = value;
                    this.RaisePropertyChanged("nomeAluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.RecuperaDados.Turma turma {
            get {
                return this.turmaField;
            }
            set {
                if ((object.ReferenceEquals(this.turmaField, value) != true)) {
                    this.turmaField = value;
                    this.RaisePropertyChanged("turma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bloco", Namespace="http://schemas.datacontract.org/2004/07/ServiceRecuperaDados")]
    [System.SerializableAttribute()]
    public partial class Bloco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestApp.RecuperaDados.Curso cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid idBlocoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TestApp.RecuperaDados.Modulo> modulosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeBlocoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestApp.RecuperaDados.Curso curso {
            get {
                return this.cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.cursoField, value) != true)) {
                    this.cursoField = value;
                    this.RaisePropertyChanged("curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid idBloco {
            get {
                return this.idBlocoField;
            }
            set {
                if ((this.idBlocoField.Equals(value) != true)) {
                    this.idBlocoField = value;
                    this.RaisePropertyChanged("idBloco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TestApp.RecuperaDados.Modulo> modulos {
            get {
                return this.modulosField;
            }
            set {
                if ((object.ReferenceEquals(this.modulosField, value) != true)) {
                    this.modulosField = value;
                    this.RaisePropertyChanged("modulos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeBloco {
            get {
                return this.nomeBlocoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeBlocoField, value) != true)) {
                    this.nomeBlocoField = value;
                    this.RaisePropertyChanged("nomeBloco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecuperaDados.IRecuperaDados")]
    public interface IRecuperaDados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaCurso", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaCursoResponse")]
        void adicionaCurso(TestApp.RecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaCurso", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaCursoResponse")]
        System.Threading.Tasks.Task adicionaCursoAsync(TestApp.RecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaTurmaResponse")]
        void adicionaTurma(TestApp.RecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaTurmaResponse")]
        System.Threading.Tasks.Task adicionaTurmaAsync(TestApp.RecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaAluno", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaAlunoResponse")]
        void adicionaAluno(TestApp.RecuperaDados.Aluno aluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaAluno", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaAlunoResponse")]
        System.Threading.Tasks.Task adicionaAlunoAsync(TestApp.RecuperaDados.Aluno aluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaProfessor", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaProfessorResponse")]
        void adicionaProfessor(TestApp.RecuperaDados.Professor professor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/adicionaProfessor", ReplyAction="http://tempuri.org/IRecuperaDados/adicionaProfessorResponse")]
        System.Threading.Tasks.Task adicionaProfessorAsync(TestApp.RecuperaDados.Professor professor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarAlunosResponse")]
        void apagarAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarAlunosResponse")]
        System.Threading.Tasks.Task apagarAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/apagarProfessoresResponse")]
        void apagarProfessores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/apagarProfessoresResponse")]
        System.Threading.Tasks.Task apagarProfessoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/apagarTurmasResponse")]
        void apagarTurmas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/apagarTurmasResponse")]
        System.Threading.Tasks.Task apagarTurmasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarCursos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarCursosResponse")]
        void apagarCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/apagarCursos", ReplyAction="http://tempuri.org/IRecuperaDados/apagarCursosResponse")]
        System.Threading.Tasks.Task apagarCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaAlunosResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> RecuperaAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaAlunos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaAlunosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Aluno>> RecuperaAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaProfessoresResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Professor> RecuperaProfessores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaProfessores", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaProfessoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Professor>> RecuperaProfessoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaCursos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaCursosResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Curso> RecuperaCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaCursos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaCursosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Curso>> RecuperaCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaTurmasResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Turma> RecuperaTurmas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaTurmas", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaTurmasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Turma>> RecuperaTurmasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaModulos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaModulosResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Modulo> RecuperaModulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/RecuperaModulos", ReplyAction="http://tempuri.org/IRecuperaDados/RecuperaModulosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Modulo>> RecuperaModulosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> ListaDeAlunosDaTurma(TestApp.RecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurma", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Aluno>> ListaDeAlunosDaTurmaAsync(TestApp.RecuperaDados.Turma turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaPorNome", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaPorNomeResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> ListaDeAlunosDaTurmaPorNome(string turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaPorNome", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeAlunosDaTurmaPorNomeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Aluno>> ListaDeAlunosDaTurmaPorNomeAsync(string turma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCurso", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCursoResponse")]
        System.Collections.Generic.List<TestApp.RecuperaDados.Turma> ListaDeTurmasDoCurso(TestApp.RecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCurso", ReplyAction="http://tempuri.org/IRecuperaDados/ListaDeTurmasDoCursoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Turma>> ListaDeTurmasDoCursoAsync(TestApp.RecuperaDados.Curso curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/turmaPorID", ReplyAction="http://tempuri.org/IRecuperaDados/turmaPorIDResponse")]
        TestApp.RecuperaDados.Turma turmaPorID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/turmaPorID", ReplyAction="http://tempuri.org/IRecuperaDados/turmaPorIDResponse")]
        System.Threading.Tasks.Task<TestApp.RecuperaDados.Turma> turmaPorIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/turmaPorNome", ReplyAction="http://tempuri.org/IRecuperaDados/turmaPorNomeResponse")]
        TestApp.RecuperaDados.Turma turmaPorNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/turmaPorNome", ReplyAction="http://tempuri.org/IRecuperaDados/turmaPorNomeResponse")]
        System.Threading.Tasks.Task<TestApp.RecuperaDados.Turma> turmaPorNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/alunoPorId", ReplyAction="http://tempuri.org/IRecuperaDados/alunoPorIdResponse")]
        TestApp.RecuperaDados.Aluno alunoPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/alunoPorId", ReplyAction="http://tempuri.org/IRecuperaDados/alunoPorIdResponse")]
        System.Threading.Tasks.Task<TestApp.RecuperaDados.Aluno> alunoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/alunoPorNome", ReplyAction="http://tempuri.org/IRecuperaDados/alunoPorNomeResponse")]
        TestApp.RecuperaDados.Aluno alunoPorNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperaDados/alunoPorNome", ReplyAction="http://tempuri.org/IRecuperaDados/alunoPorNomeResponse")]
        System.Threading.Tasks.Task<TestApp.RecuperaDados.Aluno> alunoPorNomeAsync(string nome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecuperaDadosChannel : TestApp.RecuperaDados.IRecuperaDados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecuperaDadosClient : System.ServiceModel.ClientBase<TestApp.RecuperaDados.IRecuperaDados>, TestApp.RecuperaDados.IRecuperaDados {
        
        public RecuperaDadosClient() {
        }
        
        public RecuperaDadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecuperaDadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperaDadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperaDadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void adicionaCurso(TestApp.RecuperaDados.Curso curso) {
            base.Channel.adicionaCurso(curso);
        }
        
        public System.Threading.Tasks.Task adicionaCursoAsync(TestApp.RecuperaDados.Curso curso) {
            return base.Channel.adicionaCursoAsync(curso);
        }
        
        public void adicionaTurma(TestApp.RecuperaDados.Turma turma) {
            base.Channel.adicionaTurma(turma);
        }
        
        public System.Threading.Tasks.Task adicionaTurmaAsync(TestApp.RecuperaDados.Turma turma) {
            return base.Channel.adicionaTurmaAsync(turma);
        }
        
        public void adicionaAluno(TestApp.RecuperaDados.Aluno aluno) {
            base.Channel.adicionaAluno(aluno);
        }
        
        public System.Threading.Tasks.Task adicionaAlunoAsync(TestApp.RecuperaDados.Aluno aluno) {
            return base.Channel.adicionaAlunoAsync(aluno);
        }
        
        public void adicionaProfessor(TestApp.RecuperaDados.Professor professor) {
            base.Channel.adicionaProfessor(professor);
        }
        
        public System.Threading.Tasks.Task adicionaProfessorAsync(TestApp.RecuperaDados.Professor professor) {
            return base.Channel.adicionaProfessorAsync(professor);
        }
        
        public void apagarAlunos() {
            base.Channel.apagarAlunos();
        }
        
        public System.Threading.Tasks.Task apagarAlunosAsync() {
            return base.Channel.apagarAlunosAsync();
        }
        
        public void apagarProfessores() {
            base.Channel.apagarProfessores();
        }
        
        public System.Threading.Tasks.Task apagarProfessoresAsync() {
            return base.Channel.apagarProfessoresAsync();
        }
        
        public void apagarTurmas() {
            base.Channel.apagarTurmas();
        }
        
        public System.Threading.Tasks.Task apagarTurmasAsync() {
            return base.Channel.apagarTurmasAsync();
        }
        
        public void apagarCursos() {
            base.Channel.apagarCursos();
        }
        
        public System.Threading.Tasks.Task apagarCursosAsync() {
            return base.Channel.apagarCursosAsync();
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> RecuperaAlunos() {
            return base.Channel.RecuperaAlunos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Aluno>> RecuperaAlunosAsync() {
            return base.Channel.RecuperaAlunosAsync();
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Professor> RecuperaProfessores() {
            return base.Channel.RecuperaProfessores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Professor>> RecuperaProfessoresAsync() {
            return base.Channel.RecuperaProfessoresAsync();
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Curso> RecuperaCursos() {
            return base.Channel.RecuperaCursos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Curso>> RecuperaCursosAsync() {
            return base.Channel.RecuperaCursosAsync();
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Turma> RecuperaTurmas() {
            return base.Channel.RecuperaTurmas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Turma>> RecuperaTurmasAsync() {
            return base.Channel.RecuperaTurmasAsync();
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Modulo> RecuperaModulos() {
            return base.Channel.RecuperaModulos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Modulo>> RecuperaModulosAsync() {
            return base.Channel.RecuperaModulosAsync();
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> ListaDeAlunosDaTurma(TestApp.RecuperaDados.Turma turma) {
            return base.Channel.ListaDeAlunosDaTurma(turma);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Aluno>> ListaDeAlunosDaTurmaAsync(TestApp.RecuperaDados.Turma turma) {
            return base.Channel.ListaDeAlunosDaTurmaAsync(turma);
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Aluno> ListaDeAlunosDaTurmaPorNome(string turma) {
            return base.Channel.ListaDeAlunosDaTurmaPorNome(turma);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Aluno>> ListaDeAlunosDaTurmaPorNomeAsync(string turma) {
            return base.Channel.ListaDeAlunosDaTurmaPorNomeAsync(turma);
        }
        
        public System.Collections.Generic.List<TestApp.RecuperaDados.Turma> ListaDeTurmasDoCurso(TestApp.RecuperaDados.Curso curso) {
            return base.Channel.ListaDeTurmasDoCurso(curso);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TestApp.RecuperaDados.Turma>> ListaDeTurmasDoCursoAsync(TestApp.RecuperaDados.Curso curso) {
            return base.Channel.ListaDeTurmasDoCursoAsync(curso);
        }
        
        public TestApp.RecuperaDados.Turma turmaPorID(int id) {
            return base.Channel.turmaPorID(id);
        }
        
        public System.Threading.Tasks.Task<TestApp.RecuperaDados.Turma> turmaPorIDAsync(int id) {
            return base.Channel.turmaPorIDAsync(id);
        }
        
        public TestApp.RecuperaDados.Turma turmaPorNome(string nome) {
            return base.Channel.turmaPorNome(nome);
        }
        
        public System.Threading.Tasks.Task<TestApp.RecuperaDados.Turma> turmaPorNomeAsync(string nome) {
            return base.Channel.turmaPorNomeAsync(nome);
        }
        
        public TestApp.RecuperaDados.Aluno alunoPorId(int id) {
            return base.Channel.alunoPorId(id);
        }
        
        public System.Threading.Tasks.Task<TestApp.RecuperaDados.Aluno> alunoPorIdAsync(int id) {
            return base.Channel.alunoPorIdAsync(id);
        }
        
        public TestApp.RecuperaDados.Aluno alunoPorNome(string nome) {
            return base.Channel.alunoPorNome(nome);
        }
        
        public System.Threading.Tasks.Task<TestApp.RecuperaDados.Aluno> alunoPorNomeAsync(string nome) {
            return base.Channel.alunoPorNomeAsync(nome);
        }
    }
}
